micronaut:
  application:
    name: beans-service
---
datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
    #dbCreate: create-drop
    pooled: true
jpa:
  default:
    properties:
      hibernate:
#        bytecode:
#          provider: none
        hbm2ddl:
          auto: update
          # auto: create